config-version: 1 # Do not touch this

# List of valid commands that should be intercepted -> If it starts with that cmd it will intercept (For ppl without permission)
valid-commands:
  - "/f raids"
  - "/raids"
  - "/f raidtimer"
  - "/raidtimer"

# List of valid staff raid-related commands that bypass certain checks (FactionsKore Admin Permission -> "factionskore.admin.raid-claim") - All other commands will send kores help menu.
valid-staff-raid-commands:
  - "/f raids raids"
  - "/raids raids"
  - "/f raidtimer raids"
  - "/raidtimer raids"

# List of clear commands for resetting raid data (I will listen to these commands and reset my data to sync with FactionsKores Raid Timers)
valid-clear-commands:
  - "/f raids clear"
  - "/raids clear"
  - "/f raidtimer clear"
  - "/raidtimer clear"

messages:
  active-raids-header: "&6&lActive Raids:"
  no-active-raids: "&cThere are no active raids."
  active-raid: "&e{number}. &b{raidingFaction} &eis raiding &b{defendingFaction} &efor &b{timeSinceStart}m &ewith &b{timeLeft}m &eleft."
  raid-hover-text: "&eClick to view raid details."

  active-grace-header: "&d&lActive Grace Periods:"
  no-active-grace: "&cThere are no active grace periods."
  active-grace: "&e- &b{defendingFaction} &eis on grace (set by &b{raidingFaction}&e) for &b{graceTimeLeft}&e."
  grace-hover-text: "&eClick to view raid details."

gui:
  title: "&7{raiding_name}' vs {defending_name} Raid Stats"
  size: 5
  raidColour: "&c" #The {colour} colour used in GUI for raiding factions
  defendColour: "&d" #The {colour} colour used in GUI for defending factions
  filler:
    material: STAINED_GLASS_PANE
    damage: 7
    name: "&7"
  close:
    slot: 40
    material: SKULL_ITEM
    damage: 3
    url: "afd2400002ad9fbbbd0066941eb5b1a384ab9b0e48a178ee96e4d129a5208654"
    name: "&cClose"
  stats:
    overall:
      material: TNT
      name: "&aTop Overall Stats"
      damage: 0
      slot: 13
      url: ""
      lore:
        - "&7"
        - "&5Defending Faction:"
        - "&dKills: &7{defending_kills}"
        - "&dDeaths: &7{defending_deaths}"
        - "&dBlocks Placed: &7{defending_blocks_placed}"
        - "&dDamage Dealt: &7{defending_damage_dealt} ({defending_damage_dealt_hits} hits) ({defending_damage_dealt_hearts} ❤)"
        - "&dDamage Taken: &7{defending_damage_taken} ({defending_damage_taken_hits} hits) ({defending_damage_taken_hearts} ❤)"
        - "&7"
        - "&4Raiding Faction:"
        - "&cKills: &7{attacking_kills}"
        - "&cDeaths: &7{attacking_deaths}"
        - "&cDamage Dealt: &7{attacking_damage_dealt} ({attacking_damage_dealt_hits} hits) ({attacking_damage_dealt_hearts} ❤)"
        - "&cDamage Taken: &7{attacking_damage_taken} ({attacking_damage_taken_hits} hits) ({attacking_damage_taken_hearts} ❤)"
    kills:
      name: "&cTop Kills"
      material: DIAMOND_SWORD
      damage: 0
      slot: 12
      url: ""
      lore:
        - "&7"
        - "&cRaiding Faction:"
        - "{raiding_ranks}"
        - "&7"
        - "&cDefending Faction:"
        - "{defending_ranks}"
      rank: "&c{rank}. {color}{player_name} &8- &c{stat_value}"
    deaths:
      material: BONE
      damage: 0
      slot: 21
      url: ""
      name: "&4Top Deaths"
      lore:
        - "&7"
        - "&4Raiding Faction:"
        - "{raiding_ranks}"
        - "&7"
        - "&4Defending Faction:"
        - "{defending_ranks}"
      rank: "&4{rank}. {color}{player_name} &8- &4{stat_value}"
    blocks_placed:
      material: OBSIDIAN
      damage: 0
      slot: 22
      url: ""
      name: "&eTop Blocks Placed"
      lore:
        - "&7"
        - "&eDefending Faction:"
        - "{defending_ranks}"
      rank: "&e{rank}. {color}{player_name} &8- &e{stat_value}"
    damage_taken:
      material: DIAMOND_CHESTPLATE
      name: "&bTop Damage Taken"
      damage: 0
      slot: 23
      url: ""
      lore:
        - "&7"
        - "&bRaiding Faction:"
        - "{raiding_ranks}"
        - "&7"
        - "&bDefending Faction:"
        - "{defending_ranks}"
      rank: "&b{rank}. {color}{player_name} &8- &b{stat_value} ({hits} hits) ({hearts} ❤)"
    damage_given:
      material: BLAZE_POWDER
      name: "&6Top Damage Dealt"
      damage: 0
      slot: 14
      url: ""
      lore:
        - "&7"
        - "&6Raiding Faction:"
        - "{raiding_ranks}"
        - "&7"
        - "&6Defending Faction:"
        - "{defending_ranks}"
      rank: "&6{rank}. {color}{player_name} &8- &6{stat_value} ({hits} hits) ({hearts} ❤)"
