name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.description}
authors: [Xanthard, OfficialGaming]
depend: [FactionsKore, Factions, VulcanLib]
